// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

#if STEAMWORKS_ANYCPU
#nullable enable
#endif

using System;
using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

using System.Text;

namespace Steamworks
{
	public partial class InteropHelp
	{
		public static void TestIfPlatformSupported() {
#if !UNITY_EDITOR && !UNITY_STANDALONE && !UNITY_ANDROID && !STEAMWORKS_WIN && !STEAMWORKS_LIN_OSX
			throw new System.InvalidOperationException("Steamworks functions can only be called on platforms that Steam is available on.");
#endif
		}

		public static void TestIfAvailableClient() {
			TestIfPlatformSupported();
			if (CSteamAPIContext.GetSteamClient() == System.IntPtr.Zero) {
				if (!CSteamAPIContext.Init()) {
					throw new System.InvalidOperationException("Steamworks is not initialized.");
				}
			}
		}

		public static void TestIfAvailableGameServer() {
			TestIfPlatformSupported();
			if (CSteamGameServerAPIContext.GetSteamClient() == System.IntPtr.Zero) {
				if (!CSteamGameServerAPIContext.Init()) {
					throw new System.InvalidOperationException("Steamworks GameServer is not initialized.");
				}
			}
		}

		// This continues to exist for both 'out string' and strings returned by Steamworks functions.
#if !STEAMWORKS_UNSAFE_ENABLED
		public static string PtrToStringUTF8(IntPtr nativeUtf8) {
			if (nativeUtf8 == IntPtr.Zero) {
				return null;
			}

			int len = 0;

			while (Marshal.ReadByte(nativeUtf8, len) != 0) {
				++len;
			}

			if (len == 0) {
				return string.Empty;
			}

			byte[] buffer = new byte[len];
			Marshal.Copy(nativeUtf8, buffer, 0, buffer.Length);
			return Encoding.UTF8.GetString(buffer);
		}
#endif
		public static string ByteArrayToStringUTF8(byte[] buffer) {
			int length = 0;
			while (length < buffer.Length && buffer[length] != 0) {
				length++;
			}

			return Encoding.UTF8.GetString(buffer, 0, length);
		}

		public static void StringToByteArrayUTF8(string str, byte[] outArrayBuffer, int outArrayBufferSize) {
#if NET6_0_OR_GREATER
			ArgumentNullException.ThrowIfNull(outArrayBuffer);
#else
			if (outArrayBuffer == null) {
				throw new ArgumentNullException(nameof(outArrayBuffer));
			}
#endif

			int length = Encoding.UTF8.GetBytes(str, 0, str.Length, outArrayBuffer, 0);

			// do buffer capacity check
			if (length >= outArrayBuffer.Length - 1) {
				throw new ArgumentOutOfRangeException(nameof(str), length, "Encoded string length is longer than 'outArrayByffer' can hold");
			}
			outArrayBuffer[length] = 0;
		}

		// This is for 'const char *' and `char *` arguments which we need to ensure do not get GC'd while Steam is using them.
		// We can't use an ICustomMarshaler because Unity crashes when a string between 96 and 127 characters long is defined/initialized at the top of class scope...
#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX
		public class UTF8StringHandle : Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid
		{
			public UTF8StringHandle(string str)
				: base(true) {
				if (str == null) {
					SetHandle(IntPtr.Zero);
					return;
				}

				// +1 for '\0'
				byte[] strbuf = new byte[Encoding.UTF8.GetByteCount(str) + 1];
				Encoding.UTF8.GetBytes(str, 0, str.Length, strbuf, 0);
				IntPtr buffer = Marshal.AllocHGlobal(strbuf.Length);
				Marshal.Copy(strbuf, 0, buffer, strbuf.Length);

				SetHandle(buffer);
			}

			public UTF8StringHandle(int bufferSize) : base(true) {
				SetHandle(Marshal.AllocHGlobal(bufferSize + 1));
			}

#if STEAMWORKS_ANYCPU
			public string? BackToString() {
#else
			public string BackToString() {
#endif
				if (IsInvalid)
					return null;

				return PtrToStringUTF8(handle);
			}

			protected override bool ReleaseHandle() {
				if (!IsInvalid) {
					Marshal.FreeHGlobal(handle);
				}
				return true;
			}
		}
#else
		public class UTF8StringHandle : IDisposable {
			public UTF8StringHandle(string str) { }
			public void Dispose() {}
		}
#endif

		// We can't use an ICustomMarshaler because Unity dies when MarshalManagedToNative() gets called with a generic type.
		public class SteamParamStringArray : System.IDisposable
		{
			// The pointer to each AllocHGlobal() string
#if STEAMWORKS_ANYCPU
			IntPtr[]? m_Strings;
#else
			IntPtr[] m_Strings;
#endif
			// The pointer to the condensed version of m_Strings
			IntPtr m_ptrStrings;
			// The pointer to the StructureToPtr version of SteamParamStringArray_t that will get marshaled
			IntPtr m_pSteamParamStringArray;
			private bool _disposedValue;

			public SteamParamStringArray(System.Collections.Generic.IList<string> strings) {
				if (strings == null) {
					m_pSteamParamStringArray = IntPtr.Zero;
					return;
				}

				m_Strings = new IntPtr[strings.Count];
				for (int i = 0; i < strings.Count; ++i) {
					byte[] strbuf = new byte[Encoding.UTF8.GetByteCount(strings[i]) + 1];
					Encoding.UTF8.GetBytes(strings[i], 0, strings[i].Length, strbuf, 0);
					m_Strings[i] = Marshal.AllocHGlobal(strbuf.Length);
					Marshal.Copy(strbuf, 0, m_Strings[i], strbuf.Length);
				}

				m_ptrStrings = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * m_Strings.Length);
				SteamParamStringArray_t stringArray = new SteamParamStringArray_t() {
					m_ppStrings = m_ptrStrings,
					m_nNumStrings = m_Strings.Length
				};
				Marshal.Copy(m_Strings, 0, stringArray.m_ppStrings, m_Strings.Length);

				m_pSteamParamStringArray = Marshal.AllocHGlobal(Marshal.SizeOf<SteamParamStringArray_t>());
				Marshal.StructureToPtr(stringArray, m_pSteamParamStringArray, false);
			}

			public static implicit operator IntPtr(SteamParamStringArray that) {
				return that.m_pSteamParamStringArray;
			}

			protected virtual void Dispose(bool disposing) {
				if (!_disposedValue) {
					if (disposing) {
						// Part of dispose pattern. No managed resources to dispose.
					}

					// cleanup unmanaged resources
					if (m_Strings != null) {
						foreach (IntPtr ptr in m_Strings) {
							Marshal.FreeHGlobal(ptr);
						}
					}

					if (m_ptrStrings != IntPtr.Zero) {
						Marshal.FreeHGlobal(m_ptrStrings);
					}

					if (m_pSteamParamStringArray != IntPtr.Zero) {
						Marshal.FreeHGlobal(m_pSteamParamStringArray);
					}

					_disposedValue = true;
				}
			}

			~SteamParamStringArray() {
				Dispose(disposing: false);
			}

			public void Dispose() {
				// Do not change this code. Put cleanup code into the "Dispose(bool disposing)" method.
				Dispose(disposing: true);
				GC.SuppressFinalize(this);
			}
		}
	}

	// TODO - Should be IDisposable
	// MatchMaking Key-Value Pair Marshaller
	public class MMKVPMarshaller
	{
		private IntPtr m_pNativeArray;
		private IntPtr m_pArrayEntries;

		public MMKVPMarshaller(MatchMakingKeyValuePair_t[] filters) {
			if (filters == null) {
				return;
			}

			int sizeOfMMKVP = Marshal.SizeOf<MatchMakingKeyValuePair_t>();

			m_pNativeArray = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * filters.Length);
			m_pArrayEntries = Marshal.AllocHGlobal(sizeOfMMKVP * filters.Length);
			for (int i = 0; i < filters.Length; ++i) {
				Marshal.StructureToPtr(filters[i], new IntPtr(m_pArrayEntries.ToInt64() + (i * sizeOfMMKVP)), false);
			}

			Marshal.WriteIntPtr(m_pNativeArray, m_pArrayEntries);
		}

		~MMKVPMarshaller() {
			if (m_pArrayEntries != IntPtr.Zero) {
				Marshal.FreeHGlobal(m_pArrayEntries);
			}
			if (m_pNativeArray != IntPtr.Zero) {
				Marshal.FreeHGlobal(m_pNativeArray);
			}
		}

		public static implicit operator IntPtr(MMKVPMarshaller that) {
			return that.m_pNativeArray;
		}
	}
}

#endif // !DISABLESTEAMWORKS
