// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2026 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#pragma warning disable CS1591, CS1570 // Missing XML comment for publicly visible type or member, XML comment has badly formed XML

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

// We don't expose or use Packsize in the AnyCPU build.
#if !DISABLESTEAMWORKS

// If we're running in the Unity Editor we need the editors platform.
#if UNITY_EDITOR_WIN
#define VALVE_CALLBACK_PACK_LARGE
#elif UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX
#define VALVE_CALLBACK_PACK_SMALL

// Otherwise we want the target platform.
#elif UNITY_STANDALONE_WIN || STEAMWORKS_WIN
#define VALVE_CALLBACK_PACK_LARGE
#elif UNITY_ANDROID || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || STEAMWORKS_LIN_OSX
#define VALVE_CALLBACK_PACK_SMALL

// We do not want to throw a warning when we're building in Unity but for an unsupported platform. So we'll silently let this slip by.
// It would be nice if Unity itself would define 'UNITY' or something like that...
#elif UNITY_3_5 || UNITY_4_0 || UNITY_4_1 || UNITY_4_2 || UNITY_4_3 || UNITY_4_5 || UNITY_4_6 || UNITY_4_7 || UNITY_5 || UNITY_2017_1_OR_NEWER
#define VALVE_CALLBACK_PACK_SMALL

// But we do want to be explicit on the Standalone build for XNA/Monogame.
#else
#define VALVE_CALLBACK_PACK_LARGE
#warning You need to define STEAMWORKS_WIN, or STEAMWORKS_LIN_OSX. Refer to the readme for more details.
#endif

using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
using IntPtr = System.IntPtr;

namespace Steamworks {
	public static class Packsize {
#if VALVE_CALLBACK_PACK_LARGE // DO NOT Exclude this const as it is used as Packsize placeholder for the AnyCPU build.
		internal const int value = 8;
#elif VALVE_CALLBACK_PACK_SMALL
		internal const int value = 4;
#endif

#if !STEAMWORKS_ANYCPU
        /// <summary>
        /// Get assembly defined value of structure pack size in non-AnyCPU build.
        /// </summary>
		public static readonly int Value = value;

		public static bool Test() {
			int sentinelSize = Marshal.SizeOf<ValvePackingSentinel_t>();
			int subscribedFilesSize = Marshal.SizeOf<RemoteStorageEnumerateUserSubscribedFilesResult_t>();
#if VALVE_CALLBACK_PACK_LARGE
			if (sentinelSize != 32 || subscribedFilesSize != (1 + 1 + 1 + 50 + 100) * 4 + 4)
				return false;
#elif VALVE_CALLBACK_PACK_SMALL
			if (sentinelSize != 24 || subscribedFilesSize != (1 + 1 + 1 + 50 + 100) * 4)
				return false;
#endif
			return true;
		}

		[StructLayout(LayoutKind.Sequential, Pack = Packsize.value)]
		private struct ValvePackingSentinel_t {
			uint m_u32;
			ulong m_u64;
			ushort m_u16;
			double m_d;
		};
#else
        // Core packing value selection logic for AnyCPU builds. This is a bit of a HACK, but it works.
        // We set the value of structure pack size by whether running on Windows
        // to determine the correct value to use for the Packsize class.
        // What if new packsizes are introduced? Then this will break, but for now it works.

        /// <summary>
        /// Get runtime determined value of structure pack size.
        /// </summary>
        public readonly static int AnyCpuRuntimeValue = InitializeRuntimeValue();

        /// <summary>
        /// Get runtime determined value of structure pack size in AnyCPU build. Reserved for binary compatibility with other builds. Use AnyCpuRuntimeValue instead.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
		[Obsolete($"Use {nameof(AnyCpuRuntimeValue)} instead.")]
        public readonly static int Value = AnyCpuRuntimeValue;

		/// <summary>
		/// Get the runtime determined value indicating large structure pack size in AnyCPU build.
		/// </summary>
		public readonly static bool IsLargePack = AnyCpuRuntimeValue == 8;

        /// <summary>
        /// Get the runtime determined value indicating small structure pack size in AnyCPU build.
        /// </summary>
        public readonly static bool IsSmallPack = AnyCpuRuntimeValue == 4;

        private static int InitializeRuntimeValue() {
			if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
				return 8;
			else
				return 4;
		}

		/// <summary>
		/// No effect in AnyCPU build, but required for binary compatibility with other builds.
		/// </summary>
		/// <returns></returns>
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Obsolete($"This method has no effect in AnyCPU builds.")]
        public static bool Test() => true;
#endif
	}
}

#endif // !DISABLESTEAMWORKS
