// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

namespace Steamworks {
	public static class Version {
		// TODO: MANUAL edit this file on each targeting Steamworks API update
		public const string SteamworksNETVersion = "2025.163.0";
		public const string SteamworksSDKVersion = "1.63";
        // used to for Steamworks.NET.AnyCPU to check whether the loaded native is compatible
        public const string SteamAPIDLLVersion = "10.24.16.75";
		[System.Obsolete("SteamAPIDLLVersion is more reliable to check versions", DiagnosticId = "SNET4001")]
		public const int SteamAPIDLLSize = 274072;
        [System.Obsolete("SteamAPIDLLVersion is more reliable to check versions", DiagnosticId = "SNET4001")]
        public const int SteamAPI64DLLSize = 317080;
	}
}

#endif // !DISABLESTEAMWORKS
