// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2026 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#pragma warning disable CS1591,CS1570 // Missing XML comment for publicly visible type or member, XML comment has badly formed XML

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

namespace Steamworks {
	public static class Version {
		public const string SteamworksNETVersion = "2026.165.0";
		public const string SteamworksSDKVersion = "1.65";
		public const string SteamAPIDLLVersion = "10.73.00.09";
		public const int SteamAPIDLLSize = 280216;
		public const int SteamAPI64DLLSize = 319128;
	}
}

#endif // !DISABLESTEAMWORKS
