using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;

namespace Steamworks
{
	// another part is generated by python script, which contains the expected version.
	internal static partial class VersionChecker
	{
		public const string ExpectedVersion = Version.SteamAPIDLLVersion;

		// loaded file might from a different path than the one we expect, so we need to get the actual path of the loaded module and check its version.
		[DllImport("kernel32.dll", CharSet = CharSet.Unicode, PreserveSig = true, SetLastError = true)]
		private static extern int GetModuleFileName(
			IntPtr hModule,
			StringBuilder lpFilename,
			int nSize
		);

		internal static void CheckedGoodOrThrow(nint loadedWindowsSteamModule) {
			if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
				// other platforms is not possible to check, their versioning method is too various
				return;

			StringBuilder sbModulePath = new(65535);
			if (GetModuleFileName(loadedWindowsSteamModule, sbModulePath, sbModulePath.Capacity) != 0)
				throw new ArgumentException("Module path is longer than excepted(65535), the hard path length limit as of 2026/3/10, ",
					nameof(loadedWindowsSteamModule));

			string modulePath = sbModulePath.ToString();
			FileVersionInfo ver = FileVersionInfo.GetVersionInfo(modulePath);

			if (ver.FileVersion == VersionChecker.ExpectedVersion) {
				Debug.WriteLine($"Steamworks DLL version check passed: {ver.FileVersion}");
			} else {
				throw new SteamworksDllMismatchException($"Steamworks DLL version mismatch: expected {VersionChecker.ExpectedVersion}," +
				$" but found {ver.FileVersion}" +
				$"{Environment.NewLine}Loaded Steamworks DLL path: {modulePath}") {
					ModulePath = modulePath,
					ActualVersion = ver.FileVersion,
				};
			}
		}

		/// <summary>
		/// Represents an exception that is thrown when the Steamworks DLL version does not match the expected version required
		/// by the application.
		/// </summary>
		/// <remarks>
		/// This exception typically indicates that the Steamworks native library present at runtime is
		/// incompatible with the managed code, which may result from game engine's native plugin resolve logic error,
		/// version mismatches, incorrect deployment, or pirateware. To resolve
		/// this issue, ensure .NET SDK's NuGet functionality is used to manage the Steamworks.NET.AnyCPU dependency,
		/// and that the correct version of the Steamworks DLL is included in the application's output directory.
		/// Additionally, verify that the application is not being run in an environment where a different version of the Steamworks DLL is present,
		/// such as a modded game directory or a pirated copy of the game.
		/// </remarks>
		[Serializable]
		public class SteamworksDllMismatchException : Exception
		{
			public SteamworksDllMismatchException() { }
			public SteamworksDllMismatchException(string message) : base(message) { }
			public SteamworksDllMismatchException(string message, Exception inner) : base(message, inner) { }
			[Obsolete]
			protected SteamworksDllMismatchException(
			  System.Runtime.Serialization.SerializationInfo info,
			  System.Runtime.Serialization.StreamingContext context) : base(info, context) { }

			/// <summary>
			/// Programmitaclly access the expected version of the Steamworks DLL that is required by the Steamworks.NET.
			/// </summary>
			public string ExpectedVersion => VersionChecker.ExpectedVersion;

			public string ActualVersion { get; init; }

			public string ModulePath { get; init; }
		}
	}
}
